-- 001_schema.sql
-- Ensure user role columns and product stock exist
ALTER TABLE klant ADD COLUMN IF NOT EXISTS admin TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE klant ADD COLUMN IF NOT EXISTS medewerker TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE klant ADD COLUMN IF NOT EXISTS wachtwoord VARCHAR(255);

ALTER TABLE product ADD COLUMN IF NOT EXISTS stock INT NOT NULL DEFAULT 0;
