version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: forevertools_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: forevertools
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: forevertools_pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: student
      PMA_PASSWORD: studentpass
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
